### ISSUE TITLE
Add randomization and shuffling of the main deck

### ISSUE THREAD

**Issue by jacobwilki01** [EECS-581-Cool-Kids/Cards-Cash-Casino#15]
Inside of CardManager, add a shuffle method that randomizes the deck a couple of times, and then splits it.

Inside of CardManager, add a call to this shuffle method to the method that generates the list of cards. 

Inside of CardManager, add a method that draws from the deck and returns the card drawn. This card should be removed from the deck.

**Comment by modmo22** [comment]
So, when we're talking about the main deck for any of the games, is this the deck that will hold more than just one deck of cards?
