### ISSUE TITLE
Add discard queue and card recycling

### ISSUE THREAD

**Issue by jacobwilki01** [EECS-581-Cool-Kids/Cards-Cash-Casino#17]
Add an extra list that is the "discard queue" in CardManager.

Add a Discard method to CardManager that simply adds a given card to this Discard list.

Add a recycling method that will re-add all of the cards from the discard queue to the main list, shuffle the main list, and clear the discard list.

**Comment by eBerkley** [comment]
I based feature-discard off of feature-card-hands since the decks hadn't been pushed to develop yet. I'll open a pull req for this feature after Jacob's pr gets merged.
